ARG ERPNEXT_VERSION
FROM frappe/erpnext:${ERPNEXT_VERSION}

ARG TARGETARCH
USER root
RUN test "${TARGETARCH:-amd64}" = "amd64" \
    && apt-get update \
    && apt-get install -y --no-install-recommends procps mariadb-client \
    && rm -rf /var/lib/apt/lists/*

COPY --chown=frappe:frappe nexora_app /home/frappe/frappe-bench/apps/nexora
COPY --chown=frappe:frappe deploy/nexora /home/frappe/frappe-bench/apps/erpnext/deploy/nexora
COPY deploy/coolify/nginx-template.conf /templates/nginx/frappe.conf.template

RUN find /home/frappe/frappe-bench/apps/erpnext/deploy/nexora -type f -name '*.sh' -exec chmod 0755 {} +

USER frappe
WORKDIR /home/frappe/frappe-bench
RUN /home/frappe/frappe-bench/env/bin/pip install --no-cache-dir -e apps/nexora
