#!/usr/bin/env python3
from __future__ import annotations

COLUMNS = [
	"Identificador",
	"Fuente",
	"Requisito",
	"Módulo",
	"Implementación encontrada",
	"Archivos",
	"Commit",
	"Prueba funcional",
	"Prueba negativa",
	"Entorno",
	"Resultado esperado",
	"Resultado obtenido",
	"Evidencia",
	"Incumplimiento",
	"Severidad",
	"Corrección aplicada",
	"Commit de corrección",
	"Resultado posterior",
	"Estado",
]
GROUP_ORDER = [
	"GOV",
	"US01",
	"FI01",
	"FI02",
	"PR01",
	"CO01",
	"MM01",
	"MM02",
	"MIGO",
	"QC01",
	"CL01",
	"BI01",
	"AU01",
	"MOB",
	"PWA",
	"SCH",
	"MIG",
	"DEMO",
	"INF",
	"BAK",
	"RST",
	"DOC",
	"CERT",
]
GROUPS = {}
GROUPS["GOV"] = {
	"source": "Orden final §§1,3,6,24-31",
	"module": "Gobierno",
	"files": "`docs/reconstruction/MATRIZ_ACEPTACION_1A1.md`; `.github/workflows/construcontrol-full-certification.yml`",
	"functional": "`erpnext/construcontrol/tests/test_github_governance_standalone.py`",
	"negative": "`erpnext/construcontrol/tests/test_ci_gate_contract_standalone.py`",
	"environment": "Freeze / Branch audit",
	"items": [
		("PR único #9 y rama única de trabajo", "Todo cambio se publica solo en el PR #9"),
		("main no se modifica durante corrección", "main permanece en el SHA base hasta la fusión"),
		("Sin force push ni reescritura", "La historia es lineal y auditable"),
		("Integridad obligatoria de CI", "No existen marcadores para omitir o tolerar fallos de CI"),
		("Diff completo y ausencia de conflictos", "La rama está ahead, cero behind y es fusionable"),
		("Sin revisiones o hilos bloqueantes", "No existen solicitudes de cambios pendientes"),
		("SHA exacto congelado", "Todas las puertas ejecutan el mismo HEAD"),
		("Matriz viva 1:1", "Cada requisito crítico tiene fila y evidencia"),
	],
}
GROUPS["US01"] = {
	"source": "Orden final §9",
	"module": "Usuarios y seguridad",
	"files": "`erpnext/construcontrol/users.py`; `erpnext/construcontrol/access.py`; `erpnext/construcontrol/audit.py`",
	"functional": "`erpnext/construcontrol/tests/test_runtime_user_context.py`; `erpnext/construcontrol/tests/test_users_contract_standalone.py`",
	"negative": "`erpnext/construcontrol/tests/test_access_contract_standalone.py`",
	"environment": "Gate A / FINAL",
	"items": [
		("System Manager conserva administración completa", "Acceso backend y UI autorizado"),
		("ConstruControl Manager administra módulos y aprobaciones", "CRUD y aprobación autorizados"),
		("ConstruControl Operator opera sin administrar seguridad", "CRUD operativo limitado"),
		("ConstruControl Auditor tiene lectura y exportación", "Sin mutaciones financieras"),
		("ConstruControl Viewer solo consulta proyectos asignados", "Sin escritura ni exportación sensible"),
		("Usuario sin rol es rechazado", "API y URL directa denegadas"),
		("Acceso se limita a proyectos asignados", "No hay fuga entre proyectos"),
		("Métodos whitelisted validan permisos backend", "Ocultar botones no sustituye autorización"),
		("Archivos privados respetan permisos", "Acceso directo no autorizado es rechazado"),
		("Cuentas protegidas no pueden degradarse o eliminarse", "Usuarios críticos permanecen protegidos"),
		("Auditoría de usuarios usa escritor inmutable", "Cambios registran identidad y before/after"),
		("Perfil muestra identidad y rol efectivos", "UI coincide con backend"),
	],
}
GROUPS["FI01"] = {
	"source": "Orden final §10",
	"module": "Fondos FI01",
	"files": "`erpnext/construcontrol/finance.py`; `erpnext/construcontrol/business_rules.py`",
	"functional": "`erpnext/construcontrol/tests/test_finance_contract_standalone.py`; `erpnext/construcontrol/tests/test_funding_balances_standalone.py`; `erpnext/construcontrol/tests/test_mariadb_shared_fixtures.py`",
	"negative": "`erpnext/construcontrol/tests/test_funding_consumers_standalone.py`",
	"environment": "Gate A / Production validation",
	"items": [
		("Registrar remesas, aportes, depósitos, transferencias y efectivo", "Tipos válidos quedan trazados"),
		("Manejar moneda y tipo de cambio", "Conversión HNL determinista"),
		("Separar monto bruto, comisión y deducción", "Neto = bruto - cargos"),
		("Calcular monto neto HNL", "Redondeo y tasa correctos"),
		("Exigir referencia y proyecto", "Ingreso sin identidad es rechazado"),
		("Estados pending/received/held/cancelled", "Solo received conciliado se reconoce"),
		("Conciliación verified/reconciled", "Fondos no conciliados no quedan disponibles"),
		("Anulación y reversión", "Saldos se revierten sin borrar trazabilidad"),
		("Recibido y reconocido", "No se confunden estados"),
		("Gastado ejecutado", "Solo pagos válidos consumen fondo"),
		("Comprometido y pendiente", "Obligaciones no pagadas se separan"),
		("Disponible", "Reconocido - gastado"),
		("Proyectado", "Disponible - pendiente/comprometido según contrato"),
		("Fondos retenidos/cancelados no disponibles", "Saldo cero reconocido"),
		("No doble contabilización", "Cada fuente y movimiento se cuenta una vez"),
	],
}
GROUPS["FI02"] = {
	"source": "Orden final §11",
	"module": "Gastos FI02",
	"files": "`erpnext/construcontrol/expenses.py`; `erpnext/construcontrol/business_rules.py`; `erpnext/construcontrol/audit.py`",
	"functional": "`erpnext/construcontrol/tests/test_fi02_lifecycle_standalone.py`; `erpnext/construcontrol/tests/test_expense_status_schema_standalone.py`; `erpnext/construcontrol/tests/test_mariadb_shared_fixtures.py`",
	"negative": "`erpnext/construcontrol/tests/test_funding_consumers_standalone.py`",
	"environment": "Gate A / Production validation",
	"items": [
		("Gasto ligado a proyecto y fase", "Relaciones válidas"),
		("Proveedor y factura", "Identidad comercial completa"),
		("Número y fechas de factura", "Datos documentales persistidos"),
		("Vencimiento y cuenta por pagar", "Saldo y fecha exigibles"),
		("Orden de compra relacionada", "Trazabilidad MM02→FI02"),
		("Fuente FI01 obligatoria cuando aplica", "Consumo reconciliado"),
		("Categoría, material, unidad y cantidad", "Detalle cuantitativo"),
		("Subtotal, impuestos, retenciones y descuentos", "Total exacto"),
		("Moneda y conversión", "Total HNL coherente"),
		("Aprobación, rechazo y reapertura", "Transiciones autorizadas"),
		("Pago parcial", "Saldo remanente exacto"),
		("Pago completo", "Saldo cero y estado paid"),
		("Referencia de pago única", "Duplicado rechazado"),
		("Comprobante privado obligatorio", "Pago sin evidencia rechazado"),
		("Auditoría before/after", "Toda transición queda registrada"),
		("Factura duplicada bloqueada", "Proveedor+número no se repite"),
		("CxP duplicada bloqueada", "Una obligación canónica"),
		("Modificación financiera posterior a aprobación bloqueada", "Reapertura explícita requerida"),
		("Anulación revierte saldos", "Sin borrado destructivo"),
		("FI02 reconcilia con FI01", "Consumo del fondo coincide"),
	],
}
GROUPS["PR01"] = {
	"source": "Orden final §12",
	"module": "Proyectos y presupuesto",
	"files": "`erpnext/construcontrol/construction.py`; `erpnext/construcontrol/executive_impl.py`",
	"functional": "`erpnext/construcontrol/tests/test_business_rules_standalone.py`; `erpnext/construcontrol/tests/test_executive_contract_standalone.py`",
	"negative": "`erpnext/construcontrol/tests/test_runtime_smoke_contract_standalone.py`",
	"environment": "Gate A / FINAL",
	"items": [
		("Proyecto residencial canónico", "Un único registro fuente"),
		("Fases con responsable y fechas", "Planificación trazable"),
		("Programación y avance planificado", "Fechas coherentes"),
		("Presupuesto por proyecto/fase", "Monto base persistido"),
		("Costo real", "Derivado de gastos aprobados"),
		("Comprometido", "Contratos y CxP abiertos"),
		("Pendiente", "Obligaciones aún no pagadas"),
		("Disponible", "Presupuesto menos real/comprometido"),
		("Desviaciones y alertas", "Sobrepresupuesto y retraso visibles"),
		("Sin cálculo duplicado o actualización recursiva", "Un único cálculo canónico"),
	],
}
GROUPS["CO01"] = {
	"source": "Orden final §12",
	"module": "Contratos",
	"files": "`erpnext/construcontrol/construction.py`; `erpnext/construcontrol/expenses.py`",
	"functional": "`erpnext/construcontrol/tests/test_business_rules_standalone.py`; `erpnext/construcontrol/tests/test_mariadb_shared_fixtures.py`",
	"negative": "`erpnext/construcontrol/tests/test_fi02_lifecycle_standalone.py`",
	"environment": "Gate A / FINAL",
	"items": [
		("Contrato ligado a proyecto y contratista", "Relación válida"),
		("Monto contractual y moneda", "Valor base exacto"),
		("Anticipo", "Se descuenta una sola vez"),
		("Retención", "Se calcula y libera según estado"),
		("Pagos parciales", "Acumulado exacto"),
		("Saldo contractual", "Monto - anticipos - pagos ± retenciones"),
		("Referencia de pago única", "Duplicado rechazado"),
		("Compromiso financiero", "Contrato abierto alimenta comprometido"),
		("Anulación/reversión", "Saldos se restauran"),
		("Sin pagos o compromisos duplicados", "Idempotencia"),
	],
}
GROUPS["MM01"] = {
	"source": "Orden final §13",
	"module": "Materiales",
	"files": "`erpnext/construcontrol/inventory.py`",
	"functional": "`erpnext/construcontrol/tests/test_inventory_contract_standalone.py`",
	"negative": "`erpnext/construcontrol/tests/test_inventory_contract_standalone.py`",
	"environment": "Gate B",
	"items": [
		("Catálogo de materiales", "Identidad única"),
		("Unidades válidas", "Cantidad comparable"),
		("Categorías", "Clasificación consistente"),
		("Costo unitario", "Valor no negativo"),
		("Proyecto y fase", "Asignación trazable"),
		("Bodega", "Ubicación válida"),
	],
}
GROUPS["MM02"] = {
	"source": "Orden final §13",
	"module": "Compras",
	"files": "`erpnext/construcontrol/inventory.py`; `erpnext/construcontrol/expenses.py`",
	"functional": "`erpnext/construcontrol/tests/test_inventory_contract_standalone.py`",
	"negative": "`erpnext/construcontrol/tests/test_access_contract_standalone.py`",
	"environment": "Gate B",
	"items": [
		("Solicitud de material", "Demanda trazada"),
		("Cotizaciones comparables", "Proveedor y precio registrados"),
		("Orden de compra", "Aprobación y proveedor"),
		("Recepción parcial/completa", "Cantidad recibida exacta"),
		("Relación orden-recepción", "No recepción huérfana"),
		("Integración proveedor/compra/FI02", "CxP canónica"),
		("Duplicados de recepción bloqueados", "Idempotencia"),
		("Operación sin permisos rechazada", "Backend protegido"),
	],
}
GROUPS["MIGO"] = {
	"source": "Orden final §13",
	"module": "Inventario MIGO",
	"files": "`erpnext/construcontrol/inventory.py`",
	"functional": "`erpnext/construcontrol/tests/test_inventory_contract_standalone.py`; `erpnext/construcontrol/tests/test_mariadb_shared_fixtures.py`",
	"negative": "`erpnext/construcontrol/tests/test_inventory_contract_standalone.py`",
	"environment": "Gate B",
	"items": [
		("Entrada", "Aumenta existencia"),
		("Consumo", "Reduce existencia"),
		("Devolución", "Revierte consumo válido"),
		("Transferencia", "Origen baja y destino sube"),
		("Ajuste", "Exige justificación"),
		("Stock negativo bloqueado", "No se permite saldo menor que cero"),
		("Salida superior a existencia bloqueada", "Transacción rechazada"),
		("Movimiento duplicado bloqueado", "Clave idempotente"),
		("Transferencia inválida bloqueada", "Origen y destino válidos y distintos"),
		("Trazabilidad proyecto/fase/bodega", "Ledger completo"),
	],
}
GROUPS["QC01"] = {
	"source": "Orden final §14",
	"module": "Calidad y evidencias",
	"files": "`erpnext/construcontrol/quality.py`; `erpnext/construcontrol/quality_migration.py`; `erpnext/construcontrol/install.py`",
	"functional": "`erpnext/construcontrol/tests/test_quality_closing_contract_standalone.py`; `erpnext/construcontrol/tests/test_quality_migration_contract_standalone.py`",
	"negative": "`erpnext/construcontrol/tests/test_quality_closing_contract_standalone.py`",
	"environment": "Gate B / FINAL",
	"items": [
		("Avance por proyecto y fase", "Relaciones válidas"),
		("Porcentaje entre 0 y 100", "Rango validado"),
		("Responsable y fecha", "Campos obligatorios"),
		("Estado de calidad", "pending/passed/failed/corrective"),
		("Incidencia y acción correctiva", "Fallo requiere seguimiento"),
		("Observaciones y alerta", "Fallo no queda silencioso"),
		("Evidencia privada", "Archivo no público"),
		("Cámara, galería y PDF", "MIME y tamaño válidos"),
		("Regresión de avance autorizada", "Motivo y manager requeridos"),
		("Esquema de calidad instalado y backfill idempotente", "Campos existen antes del runtime"),
	],
}
GROUPS["CL01"] = {
	"source": "Orden final §14",
	"module": "Cierres",
	"files": "`erpnext/construcontrol/weekly_impl.py`; `erpnext/construcontrol/closing.py`",
	"functional": "`erpnext/construcontrol/tests/test_quality_closing_contract_standalone.py`; `erpnext/construcontrol/tests/test_mariadb_shared_fixtures.py`",
	"negative": "`erpnext/construcontrol/tests/test_quality_closing_contract_standalone.py`",
	"environment": "Gate B / FINAL",
	"items": [
		("Cierre semanal por proyecto", "Periodo válido"),
		("Saldo inicial", "Toma último cierre anterior"),
		("Ingresos reconocidos", "Solo FI01 válido"),
		("Gastos reales y pendientes", "Separación exacta"),
		("Comprometido", "Contratos/CxP abiertos"),
		("Saldo final y proyectado", "Fórmula reconciliada"),
		("Cierre idempotente", "Mismo snapshot no duplica"),
		("Reapertura autorizada y auditada", "Motivo obligatorio"),
	],
}
GROUPS["BI01"] = {
	"source": "Orden final §15",
	"module": "Dashboard y reportes",
	"files": "`erpnext/construcontrol/reporting.py`; `erpnext/construcontrol/reporting_summary.py`; `erpnext/construcontrol/reporting_exports.py`",
	"functional": "`erpnext/construcontrol/tests/test_bi_audit_contract_standalone.py`; `erpnext/construcontrol/tests/test_executive_contract_standalone.py`",
	"negative": "`erpnext/construcontrol/tests/test_bi_audit_contract_standalone.py`",
	"environment": "Gate B",
	"items": [
		("Dashboard canónico", "Una sola fuente de indicadores"),
		("Filtros por proyecto y fecha", "Resultados acotados"),
		("Drill-down", "Indicador abre registros fuente"),
		("Fondos", "Total coincide con FI01"),
		("Gastos y CxP", "Total coincide con FI02"),
		("Proyectos y contratos", "Indicadores reconciliados"),
		("Inventario", "Existencia coincide con ledger"),
		("Avance y cierres", "Resumen coincide con fuentes"),
		("Exportación CSV privada", "Sin acceso público"),
		("Neutralización de fórmulas CSV", "Prefijos peligrosos escapados"),
	],
}
GROUPS["AU01"] = {
	"source": "Orden final §15",
	"module": "Auditoría",
	"files": "`erpnext/construcontrol/audit.py`; `erpnext/construcontrol/users.py`",
	"functional": "`erpnext/construcontrol/tests/test_audit_contract_standalone.py`; `erpnext/construcontrol/tests/test_bi_audit_contract_standalone.py`",
	"negative": "`erpnext/construcontrol/tests/test_audit_contract_standalone.py`",
	"environment": "Gate B / Independent audit",
	"items": [
		("Usuario e identidad", "Actor efectivo registrado"),
		("Rol", "Rol de negocio registrado"),
		("Acción, fecha y módulo", "Evento completo"),
		("Registro objetivo", "DocType y nombre"),
		("Valor anterior y posterior", "Diff trazable"),
		("Motivo y origen", "Contexto preservado"),
		("Correlación", "Eventos relacionados agrupables"),
		("Huella SHA-256", "Integridad verificable"),
		("Inmutabilidad", "Insert backend, sin edición/borrado"),
		("Snapshots sin secretos", "Redacción de credenciales"),
	],
}
GROUPS["MOB"] = {
	"source": "Orden final §16",
	"module": "Escritorio y móvil",
	"files": "`erpnext/construcontrol/page_registry.py`; `erpnext/construcontrol/product_pages.py`; `erpnext/construcontrol/page/`",
	"functional": "`erpnext/construcontrol/tests/test_page_registry_standalone.py`; `erpnext/construcontrol/tests/test_pwa_interface_contract_standalone.py`",
	"negative": "`erpnext/construcontrol/tests/test_page_registry_standalone.py`",
	"environment": "Gate C / FINAL",
	"items": [
		("Login y perfil", "Identidad visible"),
		("Dashboard y menú", "Rutas canónicas"),
		("Barra superior y navegación", "Sin 404"),
		("Formularios y listas", "CRUD funcional"),
		("Tablas, filtros y modales", "Interacción responsive"),
		("Mensajes y errores", "Traducidos y accionables"),
		("Cámara y galería", "Evidencias nuevas"),
		("Recarga sin pérdida de datos", "Estado persistente"),
		("Cierre y reapertura", "Acciones disponibles según rol"),
		("Sin refresco infinito, overlay o doble guardado", "UI estable"),
	],
}
GROUPS["PWA"] = {
	"source": "Orden final §16",
	"module": "PWA",
	"files": "`erpnext/public/construcontrol/manifest.webmanifest`; `erpnext/www/construcontrol-service-worker.js`; `erpnext/public/js/construcontrol_pwa.js`",
	"functional": "`erpnext/construcontrol/tests/test_pwa_interface_contract_standalone.py`",
	"negative": "`erpnext/construcontrol/tests/test_pwa_interface_contract_standalone.py`",
	"environment": "Gate C / FINAL",
	"items": [
		("Manifest válido", "Nombre, display y scope correctos"),
		("Iconos 192 y 512", "Instalación soportada"),
		("start_url canónica", "Abre dashboard"),
		("Service worker versionado", "Actualización controlada"),
		("Caché solo de assets públicos", "API/private/app no se cachean"),
		("deploy-version", "Cliente detecta redeploy"),
		("Limpieza de cachés antiguas", "No pantalla obsoleta"),
		("Comportamiento post-redeploy", "Nueva versión activa"),
	],
}
GROUPS["SCH"] = {
	"source": "Orden final §17",
	"module": "Esquema e instalación",
	"files": "`erpnext/construcontrol/install.py`; `erpnext/construcontrol/install_entrypoint.py`; `erpnext/hooks.py`",
	"functional": "`erpnext/construcontrol/tests/test_install_entrypoint_standalone.py`; `erpnext/construcontrol/tests/test_schema_metadata_contract_standalone.py`",
	"negative": "`erpnext/construcontrol/tests/test_quality_migration_contract_standalone.py`",
	"environment": "Gate A / C / FINAL",
	"items": [
		("DocTypes y DocFields canónicos", "Sin definiciones paralelas"),
		("Custom Fields no duplican DocFields", "Una sola definición"),
		("install.py y hooks coherentes", "Orden de instalación determinista"),
		("after_migrate idempotente", "Repetición segura"),
		("Pages y Workspaces canónicos", "Sin duplicados"),
		("Roles y permisos instalados", "Seguridad disponible desde inicio"),
		("Instalación limpia", "Sitio nuevo saludable"),
		("Actualización sobre base existente", "Datos conservados"),
		("Tres migraciones consecutivas", "Sin duplicados ni pérdida"),
		("Reinicio y redeploy", "Persistencia preservada"),
	],
}
GROUPS["MIG"] = {
	"source": "Orden final §18",
	"module": "Migración histórica",
	"files": "`erpnext/construcontrol/migration/`; `scripts/validate_construcontrol_data_contract.py`; `MANUAL_PASO_A_PASO.md`",
	"functional": "`erpnext/construcontrol/tests/test_runtime_smoke_contract_standalone.py`; `scripts/validate_construcontrol_data_contract.py`",
	"negative": "`scripts/validate_construcontrol_data_contract.py`",
	"environment": "Gate C / FINAL",
	"items": [
		("Supabase solo origen histórico", "No backend productivo activo"),
		("Mapa origen-destino", "Cada entidad tiene destino"),
		("Backup previo con hash", "Fuente preservada"),
		("Conteos y montos", "Conciliación cuantitativa"),
		("Relaciones y huérfanos", "Referencias validadas"),
		("Detección de duplicados", "Importación idempotente"),
		("Simulación/dry-run", "Impacto previsible"),
		("Checkpoints y rollback", "Recuperación documentada"),
		("Fotografías históricas: metadata y storage conservados", "Sin pérdida; archivos nuevos permitidos"),
		("Tres migraciones posteriores", "Estado actualizado y reproducible"),
	],
}
GROUPS["DEMO"] = {
	"source": "Orden final §19",
	"module": "Datos demo",
	"files": "`erpnext/construcontrol/demo_data.py`; `MANUAL_PASO_A_PASO.md`",
	"functional": "`erpnext/construcontrol/tests/test_infrastructure_contract_standalone.py`",
	"negative": "`erpnext/construcontrol/tests/test_infrastructure_contract_standalone.py`",
	"environment": "Gate C",
	"items": [
		("Clasificar compañías demo", "No borrar real"),
		("Clasificar productos/clientes/proveedores demo", "Inventario no destructivo"),
		("Clasificar transacciones demo", "Dependencias detectadas"),
		("No mostrar demo en producción", "Solo datos reales visibles"),
		("No borrar automáticamente datos dudosos", "Revisión humana requerida"),
	],
}
GROUPS["INF"] = {
	"source": "Orden final §20",
	"module": "Infraestructura",
	"files": "`docker-compose.yml`; `Dockerfile`; `deploy/coolify/`; `docs/deployment/AWS_COOLIFY.md`",
	"functional": "`erpnext/construcontrol/tests/test_infrastructure_contract_standalone.py`",
	"negative": "`scripts/audit_requirements_1to1.py`",
	"environment": "Gate C / Production validation / FINAL",
	"items": [
		("AWS EC2 x86_64", "Plataforma linux/amd64"),
		("Coolify + Docker Compose", "Arquitectura única"),
		("MariaDB 10.6", "Base productiva"),
		("Redis cache y queue", "Servicios privados"),
		("Backend y frontend", "Health checks"),
		("Workers short/long", "Procesamiento de colas"),
		("Scheduler", "Tareas periódicas"),
		("WebSocket", "Eventos en tiempo real"),
		("Volúmenes persistentes", "DB/sites/logs no efímeros"),
		("HTTPS y URL externa", "Proxy coherente"),
		("Puertos DB/Redis no públicos", "Aislamiento"),
		("Archivos privados", "Volumen y permisos"),
	],
}
GROUPS["BAK"] = {
	"source": "Orden final §21",
	"module": "Backup",
	"files": "`deploy/coolify/backup-now.sh`; `scripts/archive_backup_set.py`; `scripts/verify_backup_manifest.py`",
	"functional": "`erpnext/construcontrol/tests/test_infrastructure_contract_standalone.py`; `scripts/verify_backup_manifest.py`",
	"negative": "`scripts/verify_backup_manifest.py`",
	"environment": "Gate C / Production validation / FINAL",
	"items": [
		("Backup de base", "Archivo presente y no vacío"),
		("Archivos públicos", "Archive presente"),
		("Archivos privados", "Archive presente"),
		("Configuración del sitio", "Config respaldada"),
		("Manifiesto", "Categorías y rutas completas"),
		("Tamaños", "Cada archivo reporta bytes"),
		("SHA-256", "Integridad verificable"),
		("Retención segura", "Conserva ventana configurada"),
	],
}
GROUPS["RST"] = {
	"source": "Orden final §21",
	"module": "Restore",
	"files": "`deploy/coolify/restore-verify.sh`; `scripts/verify_backup_manifest.py`",
	"functional": "`erpnext/construcontrol/tests/test_infrastructure_contract_standalone.py`",
	"negative": "`deploy/coolify/restore-verify.sh`",
	"environment": "Gate C / FINAL",
	"items": [
		("Restauración en sitio aislado", "Nunca sobre producción"),
		("Verificar manifiesto antes de restaurar", "Backup íntegro"),
		("Restaurar base", "Datos disponibles"),
		("Restaurar archivos públicos/privados", "Evidencias disponibles"),
		("Tres migraciones posteriores", "Esquema actualizado"),
		("Smoke test", "Módulos operativos"),
		("Conciliación de conteos", "Sin pérdida"),
		("Limpieza controlada del sitio de prueba", "Producción intacta"),
	],
}
GROUPS["DOC"] = {
	"source": "Orden final §22",
	"module": "Documentación",
	"files": "`MANUAL_PASO_A_PASO.md`; `README.md`; `docs/historical/README.md`; `docs/deployment/AWS_COOLIFY.md`",
	"functional": "`erpnext/construcontrol/tests/test_documentation_check_standalone.py`",
	"negative": "`erpnext/construcontrol/tests/test_documentation_check_standalone.py`",
	"environment": "Documentation Required / Gate C",
	"items": [
		("Manual único vigente", "MANUAL_PASO_A_PASO.md"),
		("Comandos completos GitHub/instalación", "Sin referencias vagas"),
		("Variables y Docker/Coolify/AWS", "Coinciden con código"),
		("Usuarios y módulos", "Uso operacional documentado"),
		("Migración y despliegue", "Secuencia reproducible"),
		("Backup, restore y rollback", "Comandos completos"),
		("Errores y mantenimiento", "Diagnóstico accionable"),
		("Manuales históricos marcados obsoletos", "No confunden producción"),
	],
}
GROUPS["CERT"] = {
	"source": "Orden final §§23-27",
	"module": "Certificación",
	"files": "`.github/workflows/construcontrol-full-certification.yml`; `.github/workflows/linters.yml`; `scripts/audit_requirements_1to1.py`",
	"functional": "`erpnext/construcontrol/tests/test_ci_gate_contract_standalone.py`; `erpnext/construcontrol/tests/test_acceptance_matrix_audit_standalone.py`",
	"negative": "`erpnext/construcontrol/tests/test_acceptance_matrix_audit_standalone.py`",
	"environment": "A / B / C / FINAL / AUDIT_1_TO_1",
	"items": [
		("Puerta A", "FI01/FI02/PR01/CO01, permisos, MariaDB y migraciones"),
		("Puerta B", "MM01/MM02/MIGO/QC01/CL01/BI01/AU01"),
		("Puerta C", "PWA, infraestructura, persistencia, backup y restore"),
		("FINAL", "Instalación limpia, redeploy y comportamiento global"),
		("Linters", "Pre-commit sin fallos"),
		("Semgrep", "Cero hallazgos bloqueantes"),
		("Semantic Commits", "Historial aceptado por política"),
		("Auditoría independiente 1:1", "Matriz completa y todas filas aprobadas"),
	],
}


def requirement_ids():
	return tuple(
		f"{group}-{index:02d}" for group in GROUP_ORDER for index, _ in enumerate(GROUPS[group]["items"], 1)
	)
