FROM frappe/erpnext:v15.117.0

USER root
COPY --chown=frappe:frappe . /home/frappe/frappe-bench/apps/erpnext
COPY deploy/render/nginx-main.conf /etc/nginx/nginx.conf
RUN chmod 0755 /home/frappe/frappe-bench/apps/erpnext/deploy/render/*.sh \
    && mkdir -p /tmp/nginx/client_temp /tmp/nginx/proxy_temp /tmp/nginx/fastcgi_temp /tmp/nginx/uwsgi_temp /tmp/nginx/scgi_temp \
    && chown -R frappe:frappe /tmp/nginx

WORKDIR /home/frappe/frappe-bench
